### ISSUE TITLE
Talk Idea: Typescript

### ISSUE THREAD

**Issue by james2doyle** [cambiecollective/vanjs#10]
- Draft Title: Getting familiar with Typescript
- Short Summary: Intro to Typescript, some of it's features, and how to migrate from JS to TS gracefully
- Length: 20-45 min full presentation
- Links: Going to refactor this to be more JS specific: https://docs.google.com/presentation/d/162PM0dXUAoIZG15m1aPDCbP21JwN_su7zHjkZgk7O2k/edit#slide=id.g1f5aa78f68_0_6

### About Me
- Name: James Doyle
- Mini-bio: Full-stack developer. Works at Sycle, upgrading the frontend of the application to React
- Would you like help with your presentation? I'm OK
- Social media link(s) (twitter, website, linkedin, etc.): @james2doyle everywhere
- Do you agree to the [VanJS Code of Conduct](https://github.com/cambiecollective/vanjs/blob/master/SPEAKING.md)? Yes

**Comment by ShMcK** [comment]
@james2doyle, I've been tasked with helping out presenters in any way needed. If you would like to bounce any ideas around or try an early dry run of your presentation for feedback, happy to help.

In terms of length, due to time constraints, it may be better to aim for 20-25 minutes with additional time for questions afterward.

**Comment by james2doyle** [comment]
@ShMcK thanks for the heads up! I will let you know if I need anything 👍

**Comment by ShMcK** [comment]
@james2doyle would you like to update the blurb for the meetup posting? Currently it's set as below:

```
Intro to Typescript, some of its features, and how to migrate from JS to TS gracefully.
```

A pretty good summary, but a bit short!

**Comment by james2doyle** [comment]
@ShMcK New intro:

> Typescript. You've heard about it, you've seen it used on a ton of big projects, even your parents are talking about it. So what is it? What problem is it solving? And finally, what overhead does it add to a project? In this presentation we will answer all these questions as well as talk about the Typescript language itself

**Comment by ShMcK** [comment]
Thanks, I've updated the meetup page: https://www.meetup.com/vancouver-javascript-developers/events/258909223/

**Comment by james2doyle** [comment]
https://docs.google.com/presentation/d/1ddWeC1QKBPqNVwkUSVy8dV700NJtySJA5sNOjV3jeMU/edit?usp=sharing

**Comment by james2doyle** [comment]
Should this get closed now?
