### ISSUE TITLE
Talk Request: async and await

### ISSUE THREAD

**Issue by apike** [cambiecollective/vanjs#13]
In addition to filing talk proposals, I think it'd be interesting to also file and track talk _requests_: talks people would interested to see. So here's mine:

----

In 2016 JavaScript got `async` and `await` for working with Promises. Most JavaScript developers have since encountered these features, but may not yet have a deep understanding of how they work in JavaScript, the pros and cons of using them compared to other ways of managing asynchronicity, and what pitfalls `await` them.

I don't _think_ we've ever had a VanJS talk on async/await or promises – what better time than now?

**Comment by neilk-vrchat** [comment]
I've made almost every mistake you can make with Promises, and now I pretty much only use async/await. I might be able to throw something together

What sort of things would you all like to see? Pick as many as you would like

1) async/await: how do I even?

2) The long, sordid tale of managing in JavaScript (at least *some* of this is necessary to discuss what async/await does, but I could go deep)

3) Bleeding edge stuff like AsyncHooks. Have you ever wanted something like a "thread-local variable" in Node, that gets passed along with your promise chain without an explicit parameter? It may be in the next version of Node. This is an active question for my day job, so it would give me another reason to find stuff out.

**Comment by neilk** [comment]
I could throw a talk together. I have been struggling with this stuff since 2013, and made just about every mistake. What would you all like to hear about?

1) Basic howto

2) The long sordid history of asynchrony in JS. Unfortunately you have to know this stuff even if you work exclusively in async/await

3) Bleeding edge stuff like AsyncHooks. (This would be an extra reason for me to solve a thing at work)

**Comment by ShMcK** [comment]
I feel like this topic, and AsyncHooks would pair well with #8.

**Comment by neilk** [comment]
@ShMcK Great idea. How about a double-header? I'll start with the history, get people up to async/await, and then I can leave advanced topics like AsyncHooks and beyond to @Qard.

I would do it just to get the inside track on AsyncHooks. I was really disappointed there wasn't a plausible way to do, for instance, request-id tracing in an Express server, but I couldn't find a public roadmap for this feature.

**Comment by neilk** [comment]
I just made a proposal #14 so IDK, do we mark this a dupe, or closed?
