### ISSUE TITLE
Talk Idea: Async and await

### ISSUE THREAD

**Issue by neilk** [cambiecollective/vanjs#14]
- **Title**: Async and await
- **Length:** (20-45 min full presentation)
- **Links:** (n/a)

At the end of this talk, you'll know how to use async/await in JavaScript, and the important gotchas.

And hopefully, you’ll also have a better sense of what’s really going on, and how to fix it when it doesn’t seem to be working.

Neil has worked on JS frontends at Wikipedia and currently hacks Node.js at VRChat.

### About Me
- **Name**: Neil Kandalgaonkar
- **Mini-bio:** Correcting mistakes by published JavaScript book authors since 1996. Helped introduce JavaScript frontends (and backends!) to Wikipedia.
- **Would you like help with your presentation?** I'm pretty good at winging it from notes, but a dry run would be great, maybe over video chat.
- **Social media link(s):** [neilk.net](https://neilk.net/), [Twitter](https://twitter.com/NeilKNet)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/cambiecollective/vanjs/blob/master/CONDUCT.md)?** yes

**Comment by ShMcK** [comment]
Love it. We may be able to fit a shorter presentation (20 mins ish) in on the same day. Promise I'll callback after awaiting a response from Jeremy.

**Comment by neilk** [comment]
So where are we with this? 

It would help if I had a date to plan around

**Comment by ShMcK** [comment]
I hoped we could fit in this month, as the topic would go well Stephen's talk this month. However, there were a lot of other valid ideas discussed - such as the need to spread out good talks across different meetups, as well as the desire to avoid rescheduling existing bookings.

I apologize, as we haven't gotten into a good swing of scheduling and booking talks. The good news is: we can definitely improve. 

Post Stephen's talk would also be a good opportunity to plug your talk as a solid follow-up.

Would you be available to speak next month? We haven't scheduled a date yet, but the goal is to run VanJS more regularly. Jeremy may follow up with more info.

**Comment by ShMcK** [comment]
@neilk Would March 28th be a possibility for you?

**Comment by neilk** [comment]
👍🏼

**Comment by ShMcK** [comment]
Great! Will verify and tag this issue.

Other than that, if there's anything we can do to help your presentation be the best it can be, drop a line in this channel.

**Comment by neilk** [comment]
So here's how I think I'm going to structure this talk. I'm a believer in the Mark-Jason Dominus style of presenting which is "get to the main point on slide 2 and continue building outward from there"

- a simple example of async and await in action
- another example
- another slightly more complicated example
- a common pitfall
- another common pitfall which reveals the nature of Promises
- Okay but what are Promises even??
- brief history of Node. callbacks -> Promises (eliding the period where Promises existed in early early Node)
- Promises are now native, AND in userspace (q.js, bluebird.js, etc)
- This means that async/await is actually an abstraction over a *standard*, not a language feature per se
- Ohhhh this is why async/await is weird, it's just sugar for Promises
- TheMoreYouKnow.mp4

Thoughts?

**Comment by ShMcK** [comment]
I like the "get to the point". Personally, I like presentations like podcasts - start with a puzzle and work your way up to the solution.

A lot of people will be familiar with Async/Await and/or promises, but maybe not the pitfalls of it.

A suggestion you don't need to follow, but there it is:
- async await in all its glory
- wait, why didn't that work? so much mystery
- where it all started - callback hell
- non-native promise libraries, defer
- native promises, resolve reject
- async/await - just promises
- not a magic bullet, async/await pitfalls (like Promise.all still for the win)
- the mystery from the beginning explained
- and now async iterators

I find if you capture peoples interest in the first minute, even when they think they already know, they'll pay attention.

**Comment by ShMcK** [comment]
A personal favorite async cartoon:
![async](https://user-images.githubusercontent.com/4660659/54656839-7294be80-4a84-11e9-8f07-2d915390c014.jpg)

**Comment by neilk** [comment]
@apike In the bio you posted on Meetup, you listed my affiliation as Sauce Labs, but I work for VRChat now

**Comment by ShMcK** [comment]
I'll update it now. Sorry about that, I should have verified the post before submitting.

**Comment by ShMcK** [comment]
@neilk could you verify the updated content: https://www.meetup.com/vancouver-javascript-developers/events/259569073/ ?

**Comment by neilk** [comment]
@ShMcK Thank you for jumping on this so quickly! I edited it a bit after you posted, can you update?

**Comment by ShMcK** [comment]
sure thing!

**Comment by neilk** [comment]
LGTM, thanks @ShMck
