### ISSUE TITLE
Talk Idea: Getting ready for the decentralized web

### ISSUE THREAD

**Issue by daffl** [cambiecollective/vanjs#17]
- **Draft Title:** Getting ready for the decentralized web
- **Length:** 35 minutes
- **Links:** Original 10 minute lightning talk slides: https://daffl.github.io/decentralized-web/

The decentralized web promises to give us more control over our data and how it is used and bring us closer to the original vision of the world wide web. In this talk I'd like to go over what it is, where things are at and how JavaScript may play a key role in a decentralized ecosystem.

### About Me

- **Name:** David Luecke
- **Mini-bio:** Open sourcerer @feathersjs, decentralizer @bidalihq, rock-climber, synthesizerer, Vancouverite, German
- **Would you like help with your presentation?** should be good
- **Social media link(s):** @daffl on GitHub and Twitter
- **Do you agree to the [VanJS Code of Conduct](https://github.com/cambiecollective/vanjs/blob/master/CONDUCT.md)?** Yes 👍

**Comment by keywordnew** [comment]
+1 to JavaScript's role in a decentralized ecosystem 💯

**Comment by ShMcK** [comment]
Interesting topic, sorry for the late notice - but @daffl would you be available for March 28th by chance?

**Comment by daffl** [comment]
Possible but I would prefer a little more time (e.g. April) do some more research and improve the demo I had.

**Comment by ShMcK** [comment]
We're still looking for a talk for Mar 28th, would this talk or #18 work? Pressed for time to lock things down at this point.

**Comment by daffl** [comment]
Fair enough. I might as well then. Let's do it 😄

**Comment by ShMcK** [comment]
Awesome, will put you down :) Thanks again!

**Comment by keywordnew** [comment]
Great talk @daffl, thank you! 👏🏽🎉👏🏽
