### ISSUE TITLE
Talk Idea: Web of Things API

### ISSUE THREAD

**Issue by jaller94** [cambiecollective/vanjs#22]
- **Title:** Web of Things API – Owning home automation via HTTP
- **Length:** 40 minutes
- **Links:**
  - [Summary](https://linuxfestnorthwest.org/conferences/2019/program/proposals/246)
  - [Slides](https://wiki.chrpaul.de/_media/web_of_things:web_of_things_api.pdf)
  - [Recording](https://wiki.chrpaul.de/_media/web_of_things:web_of_things_api.pdf)

The Web of Things is an application layer protocol for self-hosted suitable for home automation. The topics of my presentation are security concerns with regular IoT products and how to keep them local with a Raspberry Pi and the [Mozilla Things](https://iot.mozilla.org/) gateway.

For JavaScript developers the Web of Things API is amazing, because it is all built on existing protocols and JSON data. You can control you home with HTTP(S) authentication and Websockets for two-way binding.

### About Me
- **Name:** Christian Paul
- **Mini-bio:** I am a web developer with a strong interest in decentralized, self-hosted services. 
- **Would you like help with your presentation?** (feedback on notes, practice run)
- **Social media link(s):**
  - [Website: chrpaul.de](https://chrpaul.de/)
  - [Mastodon: @jaller94@mastodonten.de](https://mastodonten.de/@jaller94)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/cambiecollective/vanjs/blob/master/CONDUCT.md)?** yes

**Comment by jaller94** [comment]
I withdraw my application for a talk, as I am about to move out of Vancouver.

**Comment by keywordnew** [comment]
@jaller94 good luck for what lies ahead! 🎉
