### ISSUE TITLE
Talk Idea: Writing code to refactor code - a practical guide to Abstract Syntax Trees

### ISSUE THREAD

**Issue by oliv9286** [cambiecollective/vanjs#24]
- **Draft Title: Writing code to refactor code - a practical guide to Abstract Syntax Trees** 
- **Length:** 30 minutes
- **Links:** https://drive.google.com/file/d/15OhjMXDVfrsBX5VtRpzQ6fvFJIJJH7eY/view?usp=sharing

Earlier this year, we migrated almost two thousand files from CommonJS to ES modules using codemods based on Babel. Codemods are scripts that change source code by traversing and manipulating the Abstract Syntax Tree (AST) of each source file, targeting the nodes that we want to change and modifying them to our needs. 

This talk is intended for JavaScript developers with all levels of experience, people attending the talk will learn:

- What is the Abstract Syntax Tree
- How to use the AST to write Babel plugins
- How to use Babel plugins as codemods and as build-time transforms

The key takeaway is that working with the AST is easy, useful and fun!

### About Me
- **Name:** Olivia Zhang
- **Mini-bio:** Frontend Engineer @ ZenHub
- **Would you like help with your presentation?** Would like some feedback on my presentation, if any ares are not detailed enough/too much detail, pacing etc.
- **Social media link(s):** (twitter, website, linkedin, etc.)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/cambiecollective/vanjs/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
Hi Olivia,

Fascinating and unique topic choice. I'd already love to learn more about how you created Babel codemods.

Would you be available to give a talk in September? Unspecified date so far.

**Comment by oliv9286** [comment]
@ShMcK that'd be great! thank you so much for having me

**Comment by Qard** [comment]
If you're interested in a themed event, I could also do a talk on rewriting JavaScript AST with [esprima](https://npm.im/esprima), [escodegen](https://npm.im/escodegen), and [esquery](https://npm.im/esquery).

I've also built some of my own little helper tools on top of those for experimenting with alternative APM instrumentation methods: [ast-function-tools](https://github.com/Qard/ast-function-tools) and [node-module-compile-transform-ast](https://github.com/Qard/node-module-compile-transform-ast)

**Comment by ShMcK** [comment]
Sorry, have been active enough on here. 

@oliv9286 would September 11th work?

@Qard maybe you could help @oliv9286 with some feedback?

**Comment by oliv9286** [comment]
@ShMcK yup! thank you :)

**Comment by Qard** [comment]
I'm happy to review or provide feedback, if @oliv9286 wants it. :)

**Comment by ShMcK** [comment]
I'll put up the summary & bio on Meetup.com

@oliv9286 Please edit the following summary to your liking:

```
1. Olivia Zhang - Writing code to refactor code - a practical guide to Abstract Syntax Trees

This talk is intended for JavaScript developers with all levels of experience, people attending the talk will learn
- What is the Abstract Syntax Tree
- How to use the AST to write Babel plugins
- How to use Babel plugins as codemods and as build-time transforms
The key takeaway is that working with the AST is easy, useful and fun!

Bio: Olivia is a frontend engineer at ZenHub.
```

**Comment by ShMcK** [comment]
Hi @oliv9286, just a follow up:

Are you ready for next week's presentation? If you'd like any early feedback, let me know.

**Comment by oliv9286** [comment]
@ShMcK yes :) I might ask you for some feedback next monday

**Comment by ShMcK** [comment]
Sounds great, @Qard could have a chance to chime in too :)
