### ISSUE TITLE
Talk Idea: Clear and Performant GraphQL

### ISSUE THREAD

**Issue by argemiront** [cambiecollective/vanjs#25]
- **Draft Title: Clear and Performant GraphQL**
- **Length**: 20~40 min full presentation.
- **Links**: TBD - just a proposal at the moment.

The talk will give attention to building features in GraphQL that I found unclear at first or not well documented. I'll demonstrate:
- GraphQL basics
- Applying middleware
- Using dataloaders to cache/batch queries
- Using schema directives

### About Me

- **Name:** Argemiro Neto
- **bio:** Argemiro is a Data Engineer at Semios.
- **Would you like help with your presentation?** Feedback would be appreciated.
- **Social media link(s):** linkedin.com/in/argemironeto
- **Do you agree to the VanJS [Code of Conduct](https://github.com/cambiecollective/vanjs/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
@argemiront has taught me a lot about using GQL. Thumbs up here :)

Would you be available for Sept 11th ?

**Comment by argemiront** [comment]
> Would you be available for Sept 11th ?

September 11th is fine for me!

**Comment by ShMcK** [comment]
An early draft for the Meetup Page

@argemiront please edit to your liking - especially the Bio :)

```
2. Argemiro Neto - Clear and Performant GraphQL

The talk will give attention to building features in GraphQL that I found unclear at first or not well documented. I'll demonstrate:
- GraphQL basics
- Applying middleware
- Using dataloaders to cache queries
- Using schema directives

Bio: Argemiro is a Data Engineer at Semios.
```
