### ISSUE TITLE
Speaker Proposal Template

### ISSUE THREAD

**Issue by ShMcK** [cambiecollective/vanjs#3]
Thoughts on creating a [github issue template](https://blog.github.com/2016-02-17-issue-and-pull-request-templates) for speaker proposals?

A template would likely include the necessary information:

### Presentation
- Title
- Summary (1-2 paragraphs)
- Target audience (beginner, intermediate, advanced)
- Length (5 mins, 25 mins, 45 min maximum)
- Links (slides, article, notes, etc.)
- Equipment Needed (audio, etc)

### Speaker Information
- Name
- Speaker Mini-bio (280 characters or less)
- Presentation history (first time, 2nd presentation)
- Would you like help with your presentation? (feedback on notes, practice run)
- Availability for presentation dates (January, February)
- Social media (twitter, website, linkedin, etc.)

### Paperwork
- Agree to code of conduct checkbox

See an example of the process from a [SeattleJS presentation topic issue](https://github.com/seattlejs/seattlejs/issues/131).

**Comment by chowdhurian** [comment]
Great idea! Template would def help the process. I've found that giving speakers a form to fill out is helpful and this is the Github equivalent.

I'd suggest some way to encourage people to keep their mini-bio...mini. Saying that we'd need to fit it into a tweet, so 280 chars, is one way.

Same goes for the title :)

Resource: [proposal form for C&C](https://docs.google.com/forms/d/10w4UnhLZDSQA9yFqDPLTsB3SlJG91wnQpZEPqx9ZF5k/viewform)

**Comment by ShMcK** [comment]
Definitely. It would save us time following up on information, while still leaving the format fairly open.

Any suggestions for editing the included information above?

**Comment by apike** [comment]
I think having a template is good, we just want to structure it in a way that it doesn't intimidate speakers, especially new ones, who may be looking for feedback and validation on their proposed topic idea before pitching an exact title, links, etc. Marking some things as optional are probably the way to go.

**Comment by apike** [comment]
Loaded up a speaking issue template – take a look and feel free to make/propose improvements!
