### ISSUE TITLE
Talk Idea: Async Iterators, a new future for streams

### ISSUE THREAD

**Issue by Qard** [cambiecollective/vanjs#8]
- **Draft Title:** Async Iterators, a new future for streams
- **Length:** Either lightning or a 20 minute talk, I can scale it to whatever is needed. 👍 

Async Iterators make for an exciting new stream-based future. They unlock a lot of possibilities that have long been quite complicated to achieve with Node.js style streams. I want to show a few examples of how async iterators can enable easier streaming of data from different sources and simplify callback and event systems.

### About Me
- **Name:** Stephen Belanger
- **Mini-bio:** I make Node.js diagnostics tooling at Elastic. I'm a Node.js core contributor and founder of the Diagnostics working group. I've been working with Node.js for about 8 years.
- **Would you like help with your presentation?** I'm always happy to accept feedback. 😸 
- **Social media link(s) (twitter, website, linkedin, etc.):** http://twitter.com/stephenbelanger
- **Do you agree to the [VanJS Code of Conduct](https://github.com/cambiecollective/vanjs/blob/master/SPEAKING.md)?** Yes. 👍

**Comment by ShMcK** [comment]
Stephen, great topic choice! 

Let us know if there's any way we can help with reviewing or giving early feedback for the talk.

If you have an early draft, or you'd like to meet up and demo it beforehand, let me know :)

**Comment by ShMcK** [comment]
20 minutes-ish sounds great
